---
- hosts: localhost
  become: yes
  
  tasks:
    - name: Include AUR tasks.
      include_tasks: ./tasks/aur.yaml
      args:
        apply:
          tags: [install, aur]
      tags:
        - [install, aur]

    - name: Include Pacman tasks.
      include_tasks: ./tasks/pacman.yaml
      args:
        apply:
          tags: [install, pacman]
      tags:
        - [install, pacman]

    - name: Include backup task.
      include_tasks: ./tasks/backup.yaml
      args:
        apply:
          tags: [backup]
      tags:
        - [backup]
