---
- name: AUR block.
  tags: aur
  block:
  - name: Gather the package facts
    package_facts:
      manager: auto
    
  - name: Get yay repository.
    git:
      repo: 'https://aur.archlinux.org/yay-bin.git'
      dest: '/tmp/yay-bin'
      clone: yes
    become_user: "{{ user }}"
    when: "'yay-bin' not in ansible_facts.packages"

  - name: Build yay-bin.
    shell: cd /tmp/yay-bin && makepkg -si
    become_user: "{{ user }}"
    when: "'yay-bin' not in ansible_facts.packages"

  - name: Install stuff.
    kewlfft.aur.aur:
      use: yay
      name: "{{ item }}"
      state: present
    with_items:
        - brave-bin
        - vivaldi
        - protonvpn-cli
        - visual-studio-code-bin
        - slack-desktop
        - telegram-desktop-bin
    become_user: "{{ user }}"
