---
- name: Pacman block.
  tags: pacman
  block:
  - name: Get kernel version.
    shell: echo "linux$(uname -r | cut -c -4 | sed 's/\.//')-virtualbox-host-modules"
    register: kernel_v

  - name: Install stuff.
    pacman:
      name: '{{ item }}'
      state: present
    with_items:
      - vim
      - git
      - openconnect
      - transmission-gtk
      - python-virtualenv
      - python-pip
      - htop
      - whois
      - bind
      - vlc
      - transmission-gtk
      - freerdp
      - remmina
      - zoom
      - "{{ kernel_v.stdout }}"
      - virtualbox
      - vagrant

  - name: Add user to vboxusers group.
    user:
      name: "{{ user }}"
      groups: vboxusers
      append: yes

  - name: Install Ansible.
    pip:
      name: "{{ item }}"
      extra_args: --user
    with_items:
      - ansible 
    become_user: "{{ user }}"
