---
- name: zshrc block.
  block:
  - name: Ensure that custom alias information line is present.
    lineinfile:
      name: "{{ zshrc }}"
      line: "######## Custom Aliases Created By Ansible ########"
      state: present
    check_mode: yes
    register: custom_alias_notify

  - name: Add alias title.
    lineinfile:
      path: "{{ zshrc }}"
      line: "\n######## Custom Aliases Created By Ansible ########"
    when: custom_alias_notify is changed

  - name: Add aliases and PATH to zshrc.
    lineinfile:
      path: "{{ zshrc }}"
      line: "{{ item }}"
    loop:
      - export scripts="/home/{{ user }}/scripts"
      - export pip_path="/home/{{ user }}/.local/bin"
      - export PATH=$PATH:$scripts:$pip_path
      - alias sv='source venv/bin/activate'
      - alias ga="git add"
      - alias gc="git commit -m"
      - alias gp="git push"
      - alias gs="git status"
      - alias gh="git config user.email 'xoovoox@protonmail.com' && git config user.name 'Lab-Brat'"
      - alias ping='ping -c 2'
    when: custom_alias_notify is changed
